takeAll: takeAll.cpp
	g++ takeAll.cpp -o takeAll
	./takeAll ../traces/short_trace1.txt

notTakeAll: notTakeAll.cpp
	g++ notTakeAll.cpp -o notTakeAll
	./notTakeAll ../traces/short_trace1.txt

clean:
	rm -rf *.o
	rm -rf takeAll
	rm -rf notTakeAll
	rm -rf output.txt
